# Generated by Django 2.1.2 on 2019-03-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('col_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('con_type', models.CharField(max_length=40)),
                ('sub_row_id', models.IntegerField(default=0)),
                ('url_link', models.URLField(default='')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['sub_row_id'],
            },
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('footer_included', models.BooleanField(default=False)),
                ('background_img', models.ImageField(null=True, upload_to='pages_background')),
                ('relates_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniwebs.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Page')),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('size', models.CharField(default='16px', max_length=4)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('bold', models.CharField(default='normal', max_length=6)),
                ('align', models.CharField(default='left', max_length=6)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=15)),
                ('web_url', models.CharField(max_length=10, unique=True)),
                ('menu_back_color', models.CharField(default='#8080FF', max_length=7)),
                ('menu_text_color', models.CharField(default='#000000', max_length=7)),
                ('page_back_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('foot_back_color', models.CharField(default='#faebd7', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Website'),
        ),
        migrations.AddField(
            model_name='block',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Row'),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('id', 'web_url')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('title', 'id')},
        ),
    ]
