# Generated by Django 2.1.2 on 2019-03-14 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniwebs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Row'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Website'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniwebs.Content'),
        ),
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
