# Generated by Django 2.1.2 on 2019-03-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwebs', '0002_auto_20190314_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
