# Generated by Django 2.1.2 on 2019-03-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwebs', '0003_auto_20190317_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='con_type',
        ),
    ]
