# Generated by Django 2.1.2 on 2019-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwebs', '0004_remove_content_con_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='pages_background'),
        ),
    ]
