# Generated by Django 2.1.2 on 2019-03-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwebs', '0005_auto_20190323_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=12),
        ),
    ]
